config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :flights

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "flights#index"
  resources :flights
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  # Direct associations

  belongs_to :user

  # Indirect associations

  # Validations

  validates :departs_at, presence: true

  # Scopes

  def to_s
    user.to_s
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Direct associations
  has_many :access_grants,
           class_name: "Doorkeeper::AccessGrant",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: "Doorkeeper::AccessToken",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many   :flights,
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :phone_number, uniqueness: true

  validates :phone_number, presence: true

  # Scopes

  def to_s
    email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/flights_controller.rb
class Api::V1::FlightsController < Api::V1::GraphitiController
  def index
    flights = FlightResource.all(params)
    respond_with(flights)
  end

  def show
    flight = FlightResource.find(params)
    respond_with(flight)
  end

  def create
    flight = FlightResource.build(params)

    if flight.save
      render jsonapi: flight, status: :created
    else
      render jsonapi_errors: flight
    end
  end

  def update
    flight = FlightResource.find(params)

    if flight.update_attributes
      render jsonapi: flight
    else
      render jsonapi_errors: flight
    end
  end

  def destroy
    flight = FlightResource.find(params)

    if flight.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: flight
    end
  end
end

app/controllers/api/v1/graphiti_controller.rb
class Api::V1::GraphitiController < ApplicationController
  skip_before_action :authenticate_user!
  before_action -> { doorkeeper_authorize! :public }

  include Graphiti::Rails::Responders

  def current_resource_owner
    doorkeeper_token.resource_owner
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    base_scope = params[:id].blank? ? User.where(id: current_resource_owner) : User.all
    user = UserResource.find(params, base_scope)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :current_user_must_be_flight_user,
                only: %i[edit update destroy]

  before_action :set_flight, only: %i[show edit update destroy]

  def index
    @q = current_user.flights.ransack(params[:q])
    @flights = @q.result(distinct: true).includes(:user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @flight = Flight.new
  end

  def edit; end

  def create
    @flight = Flight.new(flight_params)

    if @flight.save
      message = "Flight was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @flight, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @flight.update(flight_params)
      redirect_to @flight, notice: "Flight was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @flight.destroy
    message = "Flight was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to flights_url, notice: message
    end
  end

  private

  def current_user_must_be_flight_user
    set_flight
    unless current_user == @flight.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_flight
    @flight = Flight.find(params[:id])
  end

  def flight_params
    params.require(:flight).permit(:user_id, :departs_at, :description,
                                   :alert_sent)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @flight = Flight.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collapse_search_form
    if params[:q].blank?
      "collapse"
    else
      ""
    end
  end

  def link_to_show_or_back(
    object,
        show_content = "Show",
        back_content = "Back",
        options = {}
  )
    if request.path == url_for(object)
      link_to back_content, :back, options
    else
      link_to show_content, object, options
    end
  end
end

app/views/flights/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Flight #<%= flight.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @flight.user.present? %>
          <%= link_to flight.user, flight.user %>
        <% end %>
      </dd>

      <dt>Departs at</dt>
      <dd><%= flight.departs_at %></dd>

      <dt>Description</dt>
      <dd><%= flight.description %></dd>

      <dt>Alert sent</dt>
      <dd><%= flight.alert_sent %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back flight, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @flight.user %>
          <%= link_to edit_flight_url(flight), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @flight.user %>
          <%= link_to flight, method: :delete, data: { confirm: "Do you really want to delete this flight?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(flight.updated_at) %> ago
  </div>
</div>

app/views/flights/_flights_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "flights_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :alert_sent_eq, "Alert sent" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :alert_sent_eq, "1", checked: ((params[:q] && params[:q][:alert_sent_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :alert_sent_eq, "0", checked: ((params[:q] && params[:q][:alert_sent_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :alert_sent_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :departs_at, "Departs at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='departs_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :departs_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Departs at greater than or equal to", :data => {:target => '#departs_atgteqPicker'} %>
          <div class="input-group-append" data-target='#departs_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='departs_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :departs_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Departs at less than or equal to", :data => {:target => '#departs_atlteqPicker'} %>
          <div class="input-group-append" data-target='#departs_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#departs_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#departs_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#departs_atgteqPicker').on("dp.change", function (e) {
              $('#departs_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#departs_atlteqPicker').on("dp.change", function (e) {
              $('#departs_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/flights" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#flights_filters">
  Show filters
</a>

app/views/flights/_form.html.erb
<% was_validated = flight.errors.any? %>

<%= form_with(model: flight, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% departs_at_class = "form-control" %>
    <% departs_at_was_invalid = flight.errors.include?(:departs_at) %>

    <% if was_validated %>
      <% if departs_at_was_invalid %>
        <% departs_at_class << " is-invalid" %>
      <% else %>
        <% departs_at_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :departs_at %>
    <%= f.datetime_select :departs_at, class: departs_at_class, placeholder: "Enter departs at" %>
    <% if departs_at_was_invalid %>
      <% flight.errors.full_messages_for(:departs_at).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = flight.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% flight.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% alert_sent_class = "form-check-input" %>
    <% alert_sent_was_invalid = flight.errors.include?(:alert_sent) %>

    <% if was_validated %>
      <% if alert_sent_was_invalid %>
        <% alert_sent_class << " is-invalid" %>
      <% else %>
        <% alert_sent_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :alert_sent, class: "form-check-label" do %>
      <%= f.check_box :alert_sent, class: alert_sent_class %> Alert sent
    <% end %>
    <% if alert_sent_was_invalid %>
      <% flight.errors.full_messages_for(:alert_sent).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/flights/_list_item.html.erb
<%= link_to flight, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= flight %>
    <small class="text-muted">
      <%= time_ago_in_words(flight.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/flights/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Flight #<%= @flight.id %>
      </h2>

      <div class="card-body">
        <%= render "form", flight: @flight %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flights/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Flights

      <%= link_to new_flight_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "flights/flights_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Flights

        <%= link_to new_flight_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @flights, partial: "list_item", as: :flight %>
      </div>
    </div>
  </div>
</div>

app/views/flights/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Flight
      </h2>

      <div class="card-body">
        <%= render "form", flight: @flight %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flights/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @flight, partial: "card", as: :flight %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    CheckInAlert
  </title>

  <%= render "shared/bootstrapcdn_assets" %>

  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta charset="utf-8">
  <style>
    body { padding-bottom: 70px }
  </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      CheckInAlert
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/flights" class="dropdown-item">
              Flights
            </a>
            <a href="/users" class="dropdown-item">
              Users
            </a>
            <a href="/rails_direct_uploads" class="dropdown-item">
              Rails Direct Uploads
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user.blank? %>
          <li class="nav-item">
            <a href="/users/sign_in" class="nav-link">
              Sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_up" class="nav-link">
              Sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/users/edit" class="nav-link">
              Edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_out" data-method="delete" class="nav-link">
              Sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Phone number</dt>
      <dd><%= user.phone_number %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_flights.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Flights

    <a data-toggle="collapse" href="#user_flights_new_form">
      Add flight
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.flights.each do |flight| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to flight, flight_path(flight) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_flights_new_form">
        <%= render partial: "users/user_flights_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_flights" %>
  </div>
</div>